// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nefibdjmhhpjqizakzqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lZmliZGptaGhwanFpemFrenF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNDk0OTksImV4cCI6MjA2NjgyNTQ5OX0.JqJFfNcnZh4cV19OQxbH6CsgaGZyEZJI7uHvSnYcgbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});